version: "3.4"

services:
  cron:
    image: "${DK_REPO_DI_HOST}:5000/grdk-backup:latest"
    environment:
      - AWS_ACCESS_KEY_ID=${DK_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DK_AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${DK_AWS_BUCKET}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s
