version: "3.4"

services:
  web:
    image: "${DK_REPO_DI_HOST}:5000/grdk-msg:latest"
    ports:
      - "8002:80"
    environment:
      - CI_GITLAB_WEBHOOK_TOKEN=${DK_MSG_GITLAB_WH_TK}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s
